### ISSUE TITLE
Entities don't disappear after death

### ISSUE THREAD

**Issue by Vladg24YT** [LilyBukkit/LilyBukkit-Core#29]
Example:  
![Screenshot from 2022-08-02 10-42-08](https://user-images.githubusercontent.com/35247077/182324266-a4d03d9e-14ee-4877-9741-4c8632a9fb66.png)

**Comment by 5GameMaker** [comment]
This is a common issue on Rosepad. It happens because client manages entity's health on its side despite being in multiplayer. `EntityDamage` (35) does have `isDead` field, which is unused for now
