### ISSUE TITLE
Exiting the boat makes it gain acceleration

### ISSUE THREAD

**Issue by Vladg24YT** [LilyBukkit/LilyBukkit-Core#33]
I guess water now functions like modern ice.

Before unmounting:
![Before](https://user-images.githubusercontent.com/35247077/183041070-bc93385e-e5fa-4028-b773-bccdd4ab902f.png)
After unmounting:
![After](https://user-images.githubusercontent.com/35247077/183041355-4d61bc73-5d9d-44bd-b474-fd3510b476f5.png)

**Comment by 5GameMaker** [comment]
Boats are client-sided on Lilypad

**Comment by MIOGMIOG** [comment]
A lot of things are client side on alpha...
